### ISSUE TITLE
Issues that need to be addressed before launch

### ISSUE THREAD

**Issue by corysimmons** [stylus/stylus-lang.com#6]
https://github.com/stylus/stylus/issues/1870#issuecomment-86706804

**Comment by kizu** [comment]
@corysimmons Can you look into what is left to do regarding the stuff before launch? I'm planning to finally rewire the new site to use the old jekyll engine this week, and if everything else is ok, we could launch it I guess :)

I've got some free time finally, so I'm planning to start working on the Stylus' docs in the next few weeks.

**Comment by corysimmons** [comment]
Sounds good. :+1:

**Comment by kizu** [comment]
Replaced the engine (all the crazy jekyll stuff) behind this repo to the one that was used at learnboost page by applying the redesign. All the new stuff is now at `gh-pages` branch, the `master` is there only if I had forgot to move something, otherwise we could delete it and live with just gh-pages.

I kept the menu structure and all the IDs as they were on the learnboost site with the only exception of moving the try.html page to the top (and applying the new design to it too): http://stylus-lang.com/try.html

There are some things that need to be fixed before we could make this the one official site, I'll try to fill up the corresponding issues during the next week. At the same time during the next week I'm going to create both a twitter account for Stylus and a public Slack for the community :)

**Comment by corysimmons** [comment]
Sounds good. Instead of creating a Slack just for Stylus maybe we should just fill the #stylus room on #frontenddevs (http://frontenddevelopers.org/)?

**Comment by kizu** [comment]
Dedicated Slack could have multiple channels and there is a lot of stuff to fill them with. Using a channel at an existing one would limit how we could use it, as throwing all the stuff like notifications from github, stackoverflow etc. would flood it up easily.

**Comment by corysimmons** [comment]
:+1:

**Comment by corysimmons** [comment]
Closing this as stale.
